spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test_sme_data_delete
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console